### PR TITLE
emplyee app changes

### PR DESCRIPTION
**Pull request by narendrag4073**
Hi @adamstep  and @lalitpatel
I did not get your github userid in the reviewer suggestions list. hence I'm tagging here.
Please do let know if you need any information.

Regards,
Narendra

### CODE REVIEW

**Comment by adamstep** [comment]
Hi Narendra, a couple of comments for issues I noticed when testing:

- can you add UI feedback for employees in the list? It's not clear that the items are clickable.
- Ideally, the radio select can be toggled by clicking on the label in addition to the radio button. This can be achieved by tying the label to the input.
- When editing an employee, sometimes the "Delete" button is disabled. It looks like this is tied to the employee role. But the role is just metadata for that user account. Delete should always work.
- When I delete Narendra, Lalit also disappears.

**Comment by narendrag4073** [comment]
Hi Adam,
I reolved those issue and pushed my changes.so please review it again and give your feedback.if any changes required, i will do.

**Comment by narendrag4073** [comment]
Hi Adam,
I reolved those issue and pushed my changes.so please review it again and
give your feedback.if any changes required, i will do.

**Comment by narendrag4073** [comment]
Hi @adamstep , I reolved those issue yesterday and pushed my changes.so please review it again and give your feedback.if any changes required, i will do.

**Comment by adamstep** [comment]
Thanks @narendrag4073 , the app works well now.

**Pull request merged**
